models:
  VIIRS/Logistic:
    C: 92.78039162510628
    class_weight: null
  VIIRS/XGBoost:
    n_estimators: 295
    learning_rate: 0.006210774366061085
    max_depth: 5
    subsample: 0.832782174114649
    colsample_bytree: 0.9308442003715536
    min_child_weight: 6
    reg_alpha: 1.9269864293373244
    reg_lambda: 2.72558524889004
    max_delta_step: 7
    focal_gamma: 0.11884178825964042
    gamma: 6.895783145601179
  NLCD/Logistic:
    C: 11.05269144569142
    class_weight: null
  NLCD/XGBoost:
    n_estimators: 238
    learning_rate: 0.01219973375274994
    max_depth: 5
    subsample: 0.7622036880815221
    colsample_bytree: 0.7259772825374698
    min_child_weight: 5
    reg_alpha: 0.012086105180462691
    reg_lambda: 2.3984792291501105
    max_delta_step: 2
    focal_gamma: 1.7260635447650585
    gamma: 1.2053527990536241
  SAIPE/Logistic:
    C: 76.82087087243589
    class_weight: null
  SAIPE/XGBoost:
    n_estimators: 485
    learning_rate: 0.0005194377999680223
    max_depth: 5
    subsample: 0.5612013860674929
    colsample_bytree: 0.9086829903263249
    min_child_weight: 13
    reg_alpha: 6.219222280071228
    reg_lambda: 0.211544557955563
    max_delta_step: 8
    focal_gamma: 0.37734285638278564
    gamma: 4.503040241498799
  Stacking/XGBoost:
    n_estimators: 596
    learning_rate: 0.00013070419195032747
    max_depth: 6
    subsample: 0.5384347919299788
    colsample_bytree: 0.6024858909447213
    min_child_weight: 8
    reg_alpha: 0.7743702135174114
    reg_lambda: 2.3067628008919714
    max_delta_step: 5
    focal_gamma: 3.1758381667368885
    gamma: 2.774777260586235
  Stacking/Logistic:
    C: 0.008664253185104335
    class_weight: null
  StackingPassthrough/XGBoost:
    n_estimators: 591
    learning_rate: 0.00021549583941832642
    max_depth: 5
    subsample: 0.5539461613165828
    colsample_bytree: 0.7434221822829121
    min_child_weight: 7
    reg_alpha: 0.6300270649626047
    reg_lambda: 0.018812790990932738
    max_delta_step: 8
    focal_gamma: 1.1526830389245335
    gamma: 1.6610412296555161
  StackingPassthrough/Logistic:
    C: 0.008664253185104335
    class_weight: null
