models:
  VIIRS/Logistic:
    C: 59.48786941555163
    class_weight: null
  VIIRS/RandomForest:
    n_estimators: 848
    max_depth: 12
    min_samples_split: 48
    min_samples_leaf: 22
    max_features: log2
    class_weight: balanced
    criterion: gini
  VIIRS/XGBoost:
    n_estimators: 597
    learning_rate: 0.06396803124274388
    max_depth: 3
    subsample: 0.8897906062934019
    colsample_bytree: 0.7709560447615021
    min_child_weight: 7
    reg_alpha: 1.6427266752811769
    reg_lambda: 0.010041532700711155
    max_delta_step: 6
    gamma: 3.020664368001405
  VIIRS/SVM:
    kernel: poly
    C: 968.3436192190226
    degree: 3
    gamma_poly: scale
    coef0: 3.2274389635804623
    shrinking: true
  SAIPE_2023/Logistic:
    C: 1.0755558201149193
    class_weight: balanced
  SAIPE_2023/XGBoost:
    n_estimators: 750
    learning_rate: 0.0054234705079926025
    max_depth: 3
    subsample: 0.6872419807649187
    colsample_bytree: 0.9937171262311015
    min_child_weight: 5
    reg_alpha: 0.1757339132047719
    reg_lambda: 0.06025208636281852
    max_delta_step: 7
    gamma: 0.8340018913945823
  SAIPE_2023/SVM:
    C: 94.48222629814344
    gamma: 0.004410652742580192
    class_weight: null
  Manifold/VIIRS:
    attn_dropout: 0.18874961570292484
    batch_size: 64
    cluster_temperature: 0.1367734992388949
    contrast_temperature: 0.11441366694389209
    dropout: 0.1233867993749514
    early_stopping_rounds: 25
    embed_dim: 64
    eval_fraction: 0.2
    global_active_eps: 0.00011103525577197583
    gnn_dim: 256
    gnn_heads: 4
    gnn_layers: 1
    in_channels: 3
    lr: 0.00013577401144623775
    n_prototypes: 16
    proj_dim: 64
    random_state: 1
    semantic_dropout: 0.15484673788684333
    semantic_hidden_dim: 512
    semantic_out_dim: 64
    w_cluster: 0.9
    w_contrast: 1.5
    w_recon: 0.9
    weight_decay: 1.0278118224157019e-05
  Manifold/USPS:
    embed_dim: 128
    semantic_out_dim: 128
    transformer_dim: 128
    transformer_heads: 4
    transformer_layers: 3
    transformer_attn_dropout: 0.0705735005856277
    semantic_proj_dim: 64
    semantic_hidden_dim: 512
    semantic_depth: 3
    semantic_dropout: 0.05396594328070074
    tabular_knn: 16
    gnn_dim: 256
    gnn_layers: 1
    gnn_heads: 4
    dropout: 0.005856839107435157
    attn_dropout: 0.13601382929333905
    global_active_eps: 5.765833652753372e-06
    contrast_temperature: 0.06347471728845229
    cluster_temperature: 0.07976464253917301
    proj_dim: 128
    lr: 0.00022495220740157595
    weight_decay: 6.1304778929598415e-06
    n_prototypes: 16
    w_contrast: 1.5
    w_cluster: 0.9
    w_recon: 0.9
    batch_size: 64
    epochs: 400
    early_stopping_rounds: 25
    eval_fraction: 0.2
    min_delta: 0.0001
  Manifold/SAIPE:
    embed_dim: 64
    semantic_out_dim: 64
    transformer_dim: 128
    transformer_heads: 8
    transformer_layers: 2
    transformer_attn_dropout: 0.012829499269756873
    semantic_proj_dim: 64
    semantic_hidden_dim: 512
    semantic_depth: 4
    semantic_dropout: 0.06371379049026474
    tabular_knn: 24
    gnn_dim: 128
    gnn_layers: 2
    gnn_heads: 8
    dropout: 0.0009390952385094132
    attn_dropout: 0.13601382929333905
    global_active_eps: 6.456897906217102e-06
    contrast_temperature: 0.2717465420642991
    cluster_temperature: 0.4583091727601093
    proj_dim: 128
    lr: 0.00010135880520523338
    weight_decay: 5.20901631137038e-06
    n_prototypes: 16
    w_contrast: 1.5
    w_cluster: 0.9
    w_recon: 0.9
    batch_size: 64
    epochs: 400
    early_stopping_rounds: 25
    eval_fraction: 0.2
    min_delta: 0.0001
