models:
  VIIRS/Logistic:
    C: 59.48786941555163
    class_weight: null
  VIIRS/RandomForest:
    n_estimators: 848
    max_depth: 12
    min_samples_split: 48
    min_samples_leaf: 22
    max_features: log2
    class_weight: balanced
    criterion: gini
  VIIRS/XGBoost:
    n_estimators: 597
    learning_rate: 0.06396803124274388
    max_depth: 3
    subsample: 0.8897906062934019
    colsample_bytree: 0.7709560447615021
    min_child_weight: 7
    reg_alpha: 1.6427266752811769
    reg_lambda: 0.010041532700711155
    max_delta_step: 6
    gamma: 3.020664368001405
  VIIRS/SVM:
    kernel: poly
    C: 968.3436192190226
    degree: 3
    gamma_poly: scale
    coef0: 3.2274389635804623
    shrinking: true
  TIGER/Logistic:
    C: 0.2560161525002872
    class_weight: null
  TIGER/RandomForest:
    n_estimators: 989
    max_depth: 15
    min_samples_split: 24
    min_samples_leaf: 22
    max_features: sqrt
    class_weight: null
    criterion: log_loss
  TIGER/XGBoost:
    n_estimators: 929
    learning_rate: 0.005521931737080449
    max_depth: 6
    subsample: 0.5680099293938581
    colsample_bytree: 0.7475481870050057
    min_child_weight: 10
    reg_alpha: 2.9682530924124775
    reg_lambda: 4.066509988551353
    max_delta_step: 6
    gamma: 1.5183959657469412
  NLCD/Logistic:
    C: 11.05269144569142
    class_weight: null
  NLCD/RandomForest:
    n_estimators: 967
    max_depth: 9
    min_samples_split: 42
    min_samples_leaf: 20
    max_features: log2
    class_weight: null
    criterion: log_loss
  NLCD/XGBoost:
    n_estimators: 245
    learning_rate: 0.009105944026265281
    max_depth: 4
    subsample: 0.6865243091425225
    colsample_bytree: 0.6977702368006411
    min_child_weight: 7
    reg_alpha: 0.027637615125314263
    reg_lambda: 4.220057397195019
    max_delta_step: 2
    focal_gamma: 0.9829118084002675
    gamma: 0.5463240777949556
  Stacking/Logistic:
    C: 0.04074732214047432
    class_weight: null
  Stacking/RandomForest:
    n_estimators: 319
    max_depth: 15
    min_samples_split: 16
    min_samples_leaf: 21
    max_features: log2
    class_weight: balanced_subsample
    criterion: gini
  Stacking/XGBoost:
    n_estimators: 124
    learning_rate: 0.00019165629915952998
    max_depth: 3
    subsample: 0.6102078185662152
    colsample_bytree: 0.7541718989459322
    min_child_weight: 9
    reg_alpha: 3.8778026279872178
    reg_lambda: 2.32478037407184
    max_delta_step: 6
    focal_gamma: 2.9334034635371005
    gamma: 0.29839729522061753
  StackingPassthrough/Logistic:
    C: 73.10116549429843
    class_weight: null
  StackingPassthrough/RandomForest:
    n_estimators: 617
    max_depth: 13
    min_samples_split: 48
    min_samples_leaf: 20
    max_features: sqrt
    class_weight: balanced_subsample
    criterion: entropy
  StackingPassthrough/XGBoost:
    n_estimators: 530
    learning_rate: 0.012686032529881085
    max_depth: 5
    subsample: 0.6140080844608817
    colsample_bytree: 0.9250529478395411
    min_child_weight: 5
    reg_alpha: 0.01521148688658053
    reg_lambda: 8.661716209528166
    max_delta_step: 4
    focal_gamma: 0.36609512503579866
    gamma: 0.19163884536273662
  CorrectAndSmooth/Stacking:
    adjacency: mobility
    correction_layers: 8
    correction_alpha: 0.006992956392083721
    smoothing_layers: 6
    smoothing_alpha: 0.6011694833853859
    autoscale: false
  CorrectAndSmooth/StackingPassthrough:
    adjacency: queen
    correction_layers: 9
    correction_alpha: 0.7453392239585575
    smoothing_layers: 11
    smoothing_alpha: 0.42658711313308856
    autoscale: false
  Stacking/EDGE:
    hidden_dims: 64-64-32
    lr: 0.00012368369651954874
    weight_decay: 0.0002812730617800568
    epochs: 1415
    batch_size: 16384
    dropout: 0.20115100084568094
    residual: false
    batch_norm: false
    dataset: VIIRS+TIGER+NLCD+COORDS
  RoundRobinStacking/Logistic:
    C: 0.019982467392329464
    class_weight: null
  RoundRobinStacking/XGBoost:
    n_estimators: 866
    learning_rate: 0.008367738635708532
    max_depth: 6
    subsample: 0.5614807805731086
    colsample_bytree: 0.7282794972942038
    min_child_weight: 16
    reg_alpha: 6.738263696848777
    reg_lambda: 48.581395854987775
    max_delta_step: 10
    scale_pos_weight: 6.459879343165354
    gamma: 0.3919782278155744
  CorrectAndSmooth/RoundRobinStacking:
    adjacency: queen
    correction_layers: 4
    correction_alpha: 0.9328461384872566
    smoothing_layers: 10
    smoothing_alpha: 0.09152769113230329
    autoscale: false
  SAIPE/Logistic:
    C: 0.9275965648123793
    class_weight: balanced
  SAIPE/XGBoost:
    n_estimators: 794
    learning_rate: 0.029786678276546068
    max_depth: 6
    subsample: 0.7511159360603011
    colsample_bytree: 0.8328594936037962
    min_child_weight: 5
    reg_alpha: 0.01987999296955997
    reg_lambda: 0.03621694052083294
    max_delta_step: 1
    gamma: 0.886755443790972
  Spatial/VIIRS:
    attn_dim: 384
    attn_dropout: 0.293586
    fc_dim: 64
    dropout: 0.1355
    lr: 0.0001905
    weight_decay: 2.69191e-06
    alpha_rps: 8.473
    beta_supcon: 1.091512
    supcon_temperature: 0.15367
    supcon_dim: 128
    batch_size: 384
  XGB/Ordinal:
    n_estimators: 754
    learning_rate: 0.005089553213697213
    max_depth: 3
    subsample: 0.7183532769654946
    colsample_bytree: 0.7830350787284195
    min_child_weight: 2
    reg_alpha: 0.0017082406215522795
    reg_lambda: 0.07262129902865576
    gamma: 0.002505891172898709
  Spatial/NLCD_ROI:
    conv_channels: 32-64-128
    fc_dim: 128
    dropout: 0.32294705653332806
    lr: 7.50195444362012e-05
    weight_decay: 0.0004734989304499476
    roi_output_size: 4
    sampling_ratio: 1
    aligned: false
  VIIRS_MANIFOLD/XGBoost:
    n_estimators: 829
    learning_rate: 0.03580703296663601
    max_depth: 3
    subsample: 0.570790770154549
    colsample_bytree: 0.6394969410212462
    min_child_weight: 16
    reg_alpha: 0.15169376117132113
    reg_lambda: 45.623853218041454
    max_delta_step: 2
    gamma: 6.1612411028932375
  SAIPE_MANIFOLD/XGBoost:
    n_estimators: 532
    learning_rate: 0.07687399379259809
    max_depth: 5
    subsample: 0.6824733335408097
    colsample_bytree: 0.9597187146215655
    min_child_weight: 5
    reg_alpha: 0.036798213912308
    reg_lambda: 0.04441171334728096
    max_delta_step: 6
    gamma: 0.37750873402513435
  SAIPE_MANIFOLD/Logistic:
    C: 96.98581118991103
    class_weight: balanced
  SAIPE_2023/Logistic:
    C: 1.0755558201149193
    class_weight: balanced
  SAIPE_2023/XGBoost:
    n_estimators: 750
    learning_rate: 0.0054234705079926025
    max_depth: 3
    subsample: 0.6872419807649187
    colsample_bytree: 0.9937171262311015
    min_child_weight: 5
    reg_alpha: 0.1757339132047719
    reg_lambda: 0.06025208636281852
    max_delta_step: 7
    gamma: 0.8340018913945823
  SAIPE_MANIFOLD/SVM:
    C: 0.8219337802562704
    gamma: 0.011574389276193617
    class_weight: null
  SAIPE_2023/SVM:
    C: 94.48222629814344
    gamma: 0.004410652742580192
    class_weight: null
  VIIRS_MANIFOLD/SVM:
    C: 15.819961002882298
    gamma: 0.0006573220471004352
    class_weight: null
  VIIRS_MANIFOLD/Logistic:
    C: 0.003925294789889173
    class_weight: balanced
  Manifold/VIIRS:
    patch_size: 32
    embed_dim: 64
    gnn_dim: 256
    gnn_layers: 3
    gnn_heads: 8
    fc_dim: 128
    dropout: 0.49764000341998593
    attn_dropout: 0.1454554590554234
    max_bag_frac: 0.8890396983442015
    alpha_rps: 2.465862332753677
    beta_supcon: 1.391295588294204
    supcon_temperature: 0.23692862364560804
    supcon_dim: 256
    lr: 0.0004867740674473713
    weight_decay: 4.36359843744835e-06
    reduce_depth: 3
    reduce_dropout: 0.13911111623750236
    batch_size: 512 
  Manifold/SAIPE:
    hidden_dim: 960
    depth: 15
    dropout: 0.1603907847207383
    mix_alpha: 0.1454840927102477
    mix_mult: 8
    beta_supcon: 0.19908565050923122
    alpha_rps: 9.053711495120458
    supcon_temperature: 0.23532826829206296
    supcon_dim: 64
    transformer_dim: 64
    transformer_tokens: 8
    transformer_heads: 8
    transformer_layers: 4
    transformer_dropout: 0.006332476775095417
    transformer_attn_dropout: 0.0505545972906838
    reduce_depth: 3
    reduce_dropout: 0.008423385773528587
    lr: 0.0001443218421793436
    weight_decay: 1.939605073877735e-06
  Manifold/USPS:
    patch_size: 64
    embed_dim: 64
    gnn_dim: 256
    gnn_layers: 2
    gnn_heads: 4
    fc_dim: 256
    dropout: 0.14076599964979272
    attn_dropout: 0.20704078249920105
    max_bag_frac: 0.8655915192396935
    alpha_rps: 2.962453183957117
    beta_supcon: 0.7028450457629686
    supcon_temperature: 0.07345789470866265
    supcon_dim: 128
    lr: 0.00013954702334818668
    weight_decay: 2.6585454599593032e-06
    reduce_depth: 2
    reduce_dropout: 0.12110007475811556
  USPS_MANIFOLD/Logistic:
    C: 0.003382286306527411
    class_weight: balanced
  Manifold/USPS_SCALAR:
    hidden_dim: 1024
    depth: 16
    dropout: 0.04573884037466514
    mix_alpha: 0.2702893664233766
    mix_mult: 8
    beta_supcon: 0.3034516557151667
    alpha_rps: 9.660696669355671
    supcon_temperature: 0.12419130720765689
    supcon_dim: 128
    transformer_dim: 128
    transformer_tokens: 8
    transformer_heads: 4
    transformer_layers: 3
    transformer_dropout: 0.17955371670665143
    transformer_attn_dropout: 0.13033822284867722
    reduce_depth: 4
    reduce_dropout: 0.02134090648790369
    lr: 0.00040057248299002506
    weight_decay: 0.0002596297219777291
