models:
  VIIRS/Logistic:
    C: 88.74704576838334
    class_weight: balanced
  VIIRS/RandomForest:
    n_estimators: 878
    max_depth: 5
    min_samples_split: 38
    min_samples_leaf: 26
    max_features: log2
    criterion: log_loss
  VIIRS/XGBoost:
    n_estimators: 857
    learning_rate: 0.0114136429146054
    max_depth: 5
    subsample: 0.5893778835469077
    colsample_bytree: 0.7452613937719975
    min_child_weight: 11
    reg_alpha: 0.1267710593233306
    reg_lambda: 0.3650545129786881
    gamma: 0.31940837489542023
  VIIRS/SVM:
    kernel: poly
    C: 968.3436192190226
    degree: 3
    gamma_poly: scale
    coef0: 3.2274389635804623
    shrinking: true
  TIGER/Logistic:
    C: 98.8997630923626
    class_weight: null
  TIGER/RandomForest:
    n_estimators: 980
    max_depth: 13
    min_samples_split: 22
    min_samples_leaf: 20
    max_features: log2
    criterion: log_loss
  TIGER/XGBoost:
    n_estimators: 821
    learning_rate: 0.005615104396686979
    max_depth: 6
    subsample: 0.5198102870984317
    colsample_bytree: 0.7285160804048925
    min_child_weight: 17
    reg_alpha: 0.8744232976636904
    reg_lambda: 0.49835861374609747
    gamma: 0.18897263858905256
  NLCD/Logistic:
    C: 1.6858411657107533
    class_weight: null
  NLCD/RandomForest:
    n_estimators: 890
    max_depth: 7
    min_samples_split: 28
    min_samples_leaf: 22
    max_features: log2
    criterion: gini
  NLCD/XGBoost:
    n_estimators: 857
    learning_rate: 0.0114136429146054
    max_depth: 5
    subsample: 0.5893778835469077
    colsample_bytree: 0.7452613937719975
    min_child_weight: 11
    reg_alpha: 0.1267710593233306
    reg_lambda: 0.3650545129786881
    gamma: 0.31940837489542023
  Stacking/Logistic:
    C: 9.943748541572582
    class_weight: null
  Stacking/RandomForest:
    n_estimators: 589
    max_depth: 14
    min_samples_split: 25
    min_samples_leaf: 20
    max_features: sqrt
    criterion: entropy
  Stacking/XGBoost:
    n_estimators: 951
    learning_rate: 0.009575483751394718
    max_depth: 5
    subsample: 0.7650981624202555
    colsample_bytree: 0.791735379765745
    min_child_weight: 19
    reg_alpha: 26.650708709266215
    reg_lambda: 59.75293637568018
    gamma: 0.3078629370840729
  CorrectAndSmooth:
    adjacency: queen
    correction_alpha: 0.19298884859834387
    smoothing_alpha: 0.003024245938392855
    correction_max_iter: 10
    smoothing_max_iter: 22
    autoscale: false
  StackingOOF/IDML:
    n_neighbors_frac: 0.1701592122936776
    n_components_frac: 0.6543533664262682
    confidence_threshold: 0.7785803926496389
    label_spreading_alpha: 0.3595141388442166
    max_iter: 3
    dataset: VIIRS+OOF+COORDS
  StackingOOF/IDML/CorrectAndSmooth:
    adjacency: metric
    correction_alpha: 0.02171923884369792
    smoothing_alpha: 0.07144050826092258
    correction_max_iter: 3
    smoothing_max_iter: 1
    autoscale: false
  StackingPassthrough/Logistic:
    C: 3.131060709581739
    class_weight: null
  StackingPassthrough/RandomForest:
    n_estimators: 155
    max_depth: 8
    min_samples_split: 43
    min_samples_leaf: 20
    max_features: log2
    criterion: gini
  StackingPassthrough/XGBoost:
    n_estimators: 893
    learning_rate: 0.0035348446686374415
    max_depth: 6
    subsample: 0.6862433424195671
    colsample_bytree: 0.6747034611430234
    min_child_weight: 7
    reg_alpha: 0.32645243669276236
    reg_lambda: 0.16101223053866057
    gamma: 5.794661658824768
  StackingOOF/GBM:
    n_estimators: 121
    max_depth: 4
    learning_rate: 0.04522622249893423
    n_negatives: 10
    hard_mining_ratio: 0.2138974010172552
    n_pos_per_anchor: 3
    anchors_per_class: 495
    candidate_k: 10
    n_neighbors: 22
    dataset: PASSTHROUGH+COORDS
