models:
  VIIRS/Logistic:
    C: 99.52085994573153
    class_weight: null
  VIIRS/RandomForest:
    n_estimators: 848
    max_depth: 12
    min_samples_split: 48
    min_samples_leaf: 22
    max_features: log2
    class_weight: balanced
    criterion: gini
  VIIRS/XGBoost:
    n_estimators: 823
    learning_rate: 0.025426938870655728
    max_depth: 4
    subsample: 0.6385399814179793
    colsample_bytree: 0.6826678534911693
    min_child_weight: 5
    reg_alpha: 0.7660450663523714
    reg_lambda: 16.256976849298017
    max_delta_step: 6
    scale_pos_weight: 4.627122879329872
    gamma: 1.1612280686225906
  VIIRS/SVM:
    kernel: poly
    C: 968.3436192190226
    degree: 3
    gamma_poly: scale
    coef0: 3.2274389635804623
    shrinking: true
  TIGER/Logistic:
    C: 0.2560161525002872
    class_weight: null
  TIGER/RandomForest:
    n_estimators: 989
    max_depth: 15
    min_samples_split: 24
    min_samples_leaf: 22
    max_features: sqrt
    class_weight: null
    criterion: log_loss
  TIGER/XGBoost:
    n_estimators: 929
    learning_rate: 0.005521931737080449
    max_depth: 6
    subsample: 0.5680099293938581
    colsample_bytree: 0.7475481870050057
    min_child_weight: 10
    reg_alpha: 2.9682530924124775
    reg_lambda: 4.066509988551353
    max_delta_step: 6
    gamma: 1.5183959657469412
  NLCD/Logistic:
    C: 11.05269144569142
    class_weight: null
  NLCD/RandomForest:
    n_estimators: 967
    max_depth: 9
    min_samples_split: 42
    min_samples_leaf: 20
    max_features: log2
    class_weight: null
    criterion: log_loss
  NLCD/XGBoost:
    n_estimators: 714
    learning_rate: 0.014037220879913838
    max_depth: 6
    subsample: 0.7075066315630809
    colsample_bytree: 0.6556514332033635
    min_child_weight: 16
    reg_alpha: 6.449307483040326
    reg_lambda: 29.570490481973412
    max_delta_step: 10
    scale_pos_weight: 7.319203235040033
    gamma: 0.3983262467985261
  Stacking/Logistic:
    C: 0.19628224813442816
    class_weight: null
  Stacking/RandomForest:
    n_estimators: 319
    max_depth: 15
    min_samples_split: 16
    min_samples_leaf: 21
    max_features: log2
    class_weight: balanced_subsample
    criterion: gini
  Stacking/XGBoost:
    n_estimators: 387
    learning_rate: 0.010051506084660817
    max_depth: 3
    subsample: 0.7865308816474262
    colsample_bytree: 0.6157624371788805
    min_child_weight: 7
    reg_alpha: 5.748291778269796
    reg_lambda: 0.114900690488732
    max_delta_step: 9
    gamma: 0.10218589483781253
  StackingPassthrough/Logistic:
    C: 91.3583297855463
    class_weight: null
  StackingPassthrough/RandomForest:
    n_estimators: 617
    max_depth: 13
    min_samples_split: 48
    min_samples_leaf: 20
    max_features: sqrt
    class_weight: balanced_subsample
    criterion: entropy
  StackingPassthrough/XGBoost:
    n_estimators: 605
    learning_rate: 0.0021163466433047787
    max_depth: 4
    subsample: 0.5305692011213698
    colsample_bytree: 0.8141212394764809
    min_child_weight: 14
    reg_alpha: 0.6847446417457085
    reg_lambda: 0.16035664192996582
    max_delta_step: 1
    gamma: 0.5657093339055935
  CorrectAndSmooth/Stacking:
    adjacency: queen
    correction_layers: 21
    correction_alpha: 0.6098470496366994
    smoothing_layers: 1
    smoothing_alpha: 0.4077997332013208
    autoscale: false
  CorrectAndSmooth/StackingPassthrough:
    adjacency: queen
    correction_layers: 7
    correction_alpha: 0.49542187614430827
    smoothing_layers: 9
    smoothing_alpha: 0.0040055116209626734
    autoscale: false
  Stacking/EDGE:
    hidden_dims: 64-64-32
    lr: 0.00012368369651954874
    weight_decay: 0.0002812730617800568
    epochs: 1415
    batch_size: 16384
    dropout: 0.20115100084568094
    residual: false
    batch_norm: false
    dataset: VIIRS+TIGER+NLCD+COORDS
  RoundRobinStacking/Logistic:
    C: 0.019982467392329464
    class_weight: null
  RoundRobinStacking/XGBoost:
    n_estimators: 866
    learning_rate: 0.008367738635708532
    max_depth: 6
    subsample: 0.5614807805731086
    colsample_bytree: 0.7282794972942038
    min_child_weight: 16
    reg_alpha: 6.738263696848777
    reg_lambda: 48.581395854987775
    max_delta_step: 10
    scale_pos_weight: 6.459879343165354
    gamma: 0.3919782278155744
  CorrectAndSmooth/RoundRobinStacking:
    adjacency: queen
    correction_layers: 4
    correction_alpha: 0.9328461384872566
    smoothing_layers: 10
    smoothing_alpha: 0.09152769113230329
    autoscale: false
  SAIPE/Logistic:
    C: 76.82087087243589
    class_weight: null
  SAIPE/XGBoost:
    n_estimators: 515
    learning_rate: 0.02195773446539457
    max_depth: 3
    subsample: 0.7559684085310096
    colsample_bytree: 0.5573413149636186
    min_child_weight: 20
    reg_alpha: 3.6774346621052136
    reg_lambda: 1.7538232373118046
    max_delta_step: 2
    scale_pos_weight: 20.67282435468935
    gamma: 0.8171478915115865
