models:
  VIIRS/Logistic:
    C: 59.48786941555163
    class_weight: null
  VIIRS/RandomForest:
    n_estimators: 848
    max_depth: 12
    min_samples_split: 48
    min_samples_leaf: 22
    max_features: log2
    class_weight: balanced
    criterion: gini
  VIIRS/XGBoost:
    n_estimators: 597
    learning_rate: 0.06396803124274388
    max_depth: 3
    subsample: 0.8897906062934019
    colsample_bytree: 0.7709560447615021
    min_child_weight: 7
    reg_alpha: 1.6427266752811769
    reg_lambda: 0.010041532700711155
    max_delta_step: 6
    gamma: 3.020664368001405
  VIIRS/SVM:
    kernel: poly
    C: 968.3436192190226
    degree: 3
    gamma_poly: scale
    coef0: 3.2274389635804623
    shrinking: true
  SAIPE_2023/Logistic:
    C: 1.0755558201149193
    class_weight: balanced
  SAIPE_2023/XGBoost:
    n_estimators: 750
    learning_rate: 0.0054234705079926025
    max_depth: 3
    subsample: 0.6872419807649187
    colsample_bytree: 0.9937171262311015
    min_child_weight: 5
    reg_alpha: 0.1757339132047719
    reg_lambda: 0.06025208636281852
    max_delta_step: 7
    gamma: 0.8340018913945823
  SAIPE_2023/SVM:
    C: 94.48222629814344
    gamma: 0.004410652742580192
    class_weight: null
