models:
  label_1:
    dataset: VIIRS
    model: Logistic
    params:
      C: 1.525162544415494
      class_weight: null
  label_2:
    dataset: NLCD
    model: XGBoost
    params:
      n_estimators: 773
      learning_rate: 0.028755267235685975
      max_depth: 5
      subsample: 0.759245244523247
      colsample_bytree: 0.5123263865963631
      min_child_weight: 15
      reg_alpha: 4.964959930689843
      reg_lambda: 11.117939225850538
      max_delta_step: 9
      scale_pos_weight: 2.300090004677563
      gamma: 7.720143315784484
  label_3:
    dataset: NLCD
    model: Logistic
    params:
      C: 2.6156676357487827
      class_weight: null
  label_4:
    dataset: VIIRS
    model: XGBoost
    params:
      n_estimators: 537
      learning_rate: 0.07423917984191936
      max_depth: 4
      subsample: 0.5321117275446273
      colsample_bytree: 0.682271806362216
      min_child_weight: 10
      reg_alpha: 2.8470430762508165
      reg_lambda: 25.031310421966573
      max_delta_step: 8
      scale_pos_weight: 1.21283066358846
      gamma: 9.571979750134197
  label_5:
    dataset: NLCD
    model: XGBoost
    params:
      n_estimators: 883
      learning_rate: 0.01039592763457778
      max_depth: 6
      subsample: 0.5082185270986139
      colsample_bytree: 0.7314519719365967
      min_child_weight: 19
      reg_alpha: 4.62120389502102
      reg_lambda: 47.47374367270144
      max_delta_step: 8
      scale_pos_weight: 1.1091007644745023
      gamma: 0.7153059033457281
  label_6:
    dataset: NLCD
    model: RandomForest
    params:
      n_estimators: 950
      max_depth: 13
      min_samples_split: 52
      min_samples_leaf: 23
      max_features: log2
      class_weight: null
      criterion: gini
